language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-require-php' ]; then cd .. && eval "mv $currentfolder generator-angular-require-php" && cd generator-angular-require-php; fi

